"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const script = fs.readFileSync(path.join(root, "script.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");

assert.match(html, /data-save-current-group>Bu Sınav Grubunu Kaydet<\/button>/);
assert.match(html, /data-finish-document-upload>Devam Et<\/button>/);
assert.match(html, /data-classified-groups/);
assert.match(html, /class="saved-groups-tables" data-saved-groups-list/);
assert.match(html, /data-question-count-recovery/);
assert.match(html, /data-prep-field="course"/);
assert.match(html, /data-prep-field="schoolType"/);
assert.match(html, /data-prep-field="grade"/);
assert.match(html, /data-prep-field="courseType"/);
assert.match(html, /Okul türü, MAHİR'in başvuracağı öğretim programı ve RAG kaynaklarını belirler/);
assert.match(html, /OCR dersi sınıflandırmaz/);
assert.match(html, /Soru Sütunlarını Oluştur/);
assert.match(html, /Öğrenme çıktısı eşleştirmesi sınav grubu seçildikten sonra yapılacaktır/);
assert.match(html, /KVKK veri minimizasyonu:/);
assert.match(html, /<tr><th>Sınıf\/Şube<\/th><td colspan="5">9-A<\/td><\/tr>/);
assert.match(html, /<tr><th>Sınav Türü<\/th><td colspan="5">Yazılı<\/td><\/tr>/);
assert.match(html, /Sınıf\/şube \(ör\. 9-A\) ile sınav türü \(Yazılı, Dinleme veya Konuşma\) açıkça belirtilmelidir/);

assert.match(script, /const detectedGroups = hasFileNameExamEvidence/);
assert.match(script, /legacyRowExplosion/);
assert.match(script, /data-apply-recovered-question-count/);
assert.match(script, /Math\.min\(50, detectedQuestionCount\)/);
assert.match(script, /azami puanı sıfırdan büyük olmalıdır/);
assert.match(script, /Hiçbir kayıt oluşturulmadı/);
assert.match(script, /workflowStatus: "pending"/);
assert.match(script, /const examGroupLabel/);
assert.match(script, /rolesUsingCourse/);
assert.match(script, /updateRoleDependentVisibility/);
assert.match(script, /rolesUsingAllGrades/);
assert.match(script, /roleUsesAllGrades\(\) \? \["Tümü", \.\.\.grades\] : grades/);
assert.match(html, />Devam Et<\/button>/);
assert.match(script, /roleUsesMultipleDataSources/);
assert.match(script, /currentRole\(\) === "Branş Öğretmeni"/);
assert.match(script, /dataSourceCard\.hidden = !multipleDataSources/);
assert.match(script, /schoolType: getValue\("schoolType"\)/);
assert.match(script, /courseType: getValue\("courseType"\)/);
assert.match(script, /sınav türü ve sınıf\/şubeye göre/i);
assert.match(script, /const showFinalReview = \(\) =>/);
assert.match(script, /const startOutcomeSelection = async/);
assert.match(script, /processedDocumentKeys\.size \+ newSessionDocuments\.length > 100/);
assert.match(script, /fileInput\.multiple = true/);
assert.match(script, /Word, PDF veya Excel \(\.xlsx\) · Tek seçimde en fazla 100 dosya/);
assert.match(script, /birini ya da birden fazlasını seçiniz\. MAHİR evrakları sınıf\/şube ve sınav türüne göre ayırır/);
assert.doesNotMatch(script, /const sourceFile = payload\.fileName/);
assert.match(script, /referenceCell\.textContent = row\.dataset\.studentNo \|\| row\.dataset\.technicalId/);
assert.match(script, /studentNo: row\.dataset\.studentNo \|\| ""/);
assert.match(script, /contextData\.classSection = detectedClassSection/);
assert.match(script, /Öğrenme Eksiklikleri ve Destek İhtiyaçları Değerlendirme Raporu/);
assert.match(script, /createOutcomeCombobox/);
assert.match(script, /const weight = selected\.length \? 1 \/ selected\.length : 0/);
assert.match(script, /table\.className = "data-table saved-group-data-table"/);
assert.match(script, /group\.students\.forEach\(\(student, studentIndex\) =>/);
assert.match(script, /reviewButton\.dataset\.reviewSavedGroup/);
assert.match(script, /workflowStatus: "analyzed"/);
assert.match(html, /Sınav Gruplarına Dön/);
assert.match(script, /options\.finalReview[\s\S]*detectedQuestions\.map/);
assert.match(script, /group\.exam = \{ \.\.\.exam, componentType: component \}/);
assert.match(script, /const groupComponentType = structuredData\?\.exam\?\.componentType/);
assert.match(script, /exam\.course \|\| exam\.courseName \|\| currentCourseName\(\)/);
assert.match(script, /exam\.grade \|\| exam\.classSection \|\| currentGrade\(\)/);
assert.match(script, /Bu Tablo Üzerinde Kontrol Et/);
assert.match(script, /dataset\.inlineGroupIndex/);
assert.match(script, /group\.inlineEditing = true/);
assert.match(script, /inlineEditing: true/);
assert.match(script, /data-remove-inline-student/);
assert.match(script, /saved-group-privacy-notice/);
assert.match(script, /listbox\.style\.left = `\$\{Math\.max\(8, triggerRect\.left\)\}px`/);

assert.match(styles, /\.question-map-card\[hidden\]/);
assert.match(styles, /\.classified-group-button/);
assert.match(styles, /\.outcome-combobox-listbox[\s\S]*position: fixed;[\s\S]*z-index: 1000;/);
assert.match(styles, /\.data-table\.saved-group-data-table[\s\S]*table-layout: fixed;/);
assert.match(styles, /\.saved-group-inline-input[\s\S]*width: 100%;/);
assert.match(script, /saved-group-validation-note/);
assert.match(script, /Ayrıntılar tablonun altında gösterildi/);
assert.match(styles, /\.saved-group-validation-note/);
assert.match(html, /data-next-exam-list/);
assert.match(script, /Tüm Sınavlar Hazır — Analize Başla/);
assert.match(script, /saveCurrentOutcomeSelection/);
assert.match(script, /Analizi Başlat/);
assert.match(script, /Bu Grubun Öğrenme Çıktılarını Kaydet/);
assert.match(script, /const outcomeStructureKey/);
assert.match(script, /candidate\.sharedOutcomeSource/);
assert.match(script, /const uploadChunks = Array\.from/);
assert.match(script, /uploadChunksWithConcurrency\(uploadChunks, 3\)/);
assert.match(script, /Promise\.all\(Array\.from/);
assert.match(script, /const consolidatedGroupMap = new Map\(\)/);
assert.match(script, /existing\.students\.push/);
assert.match(script, /const examTypeFromFileName/);
assert.match(script, /examTypeSource: "file-name"/);
assert.match(script, /reliableFileType \? "file-name-confirmed" : questionShape/);
assert.match(script, /En çok tekrar eden ortak yapı tabloya uygulandı/);
assert.match(html, /Tek seferde en fazla 100 görsel/);

console.log("data-entry-flow.test.js: tüm yeni evrak akışı kontrolleri geçti.");
